#!/bin/bash
set -euo pipefail

source lib/metrics-functions.sh

# @param metric     the metric to query
# @param startDate  the date to start the query (default: 0)
#
# @return a JSON object representing an OpenTSDB average query
#
delete_query() {
    local metric=$1
    local startDate=${2:-0}
    local downSample=${3:-10s}

    echo '{
        "start":'$startDate',
        "queries":[{
            "metric":"'$metric'",
            "aggregator":"avg",
            "downsample":"'$downSample'-avg",
            "tags": {"host": "'$HOSTNAME'"}
        }]
    }'
}

delete_query load.1min | delete
